export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const studentConstants = {
  GET_GROUP_DETAILS_REQUEST: "GET_GROUP_DETAILS_REQUEST",
  GET_GROUP_DETAILS_SUCCESS: "GET_GROUP_DETAILS_SUCCESS",
  GET_GROUP_DETAILS_FAILURE: "GET_GROUP_DETAILS_FAILURE",
  GET_ALL_GROUPS_DETAILS_REQUEST: "GET_ALL_GROUPS_DETAILS_REQUEST",
  GET_ALL_GROUPS_DETAILS_SUCCESS: "GET_ALL_GROUPS_DETAILS_SUCCESS",
  GET_ALL_GROUPS_DETAILS_FAILURE: "GET_ALL_GROUPS_DETAILS_FAILURE",
};

export const submissionConstants = {
  ADD_SUBMISSION_REQUEST: "ADD_SUBMISSION_REQUEST",
  ADD_SUBMISSION_SUCCESS: "ADD_SUBMISSION_SUCCESS",
  ADD_SUBMISSION_FAILURE: "ADD_SUBMISSION_FAILURE",
  GET_SUBMISSION_DETAILS_REQUEST: "GET_SUBMISSION_DETAILS_REQUEST",
  GET_SUBMISSION_DETAILS_SUCCESS: "GET_SUBMISSION_DETAILS_SUCCESS",
  GET_SUBMISSION_DETAILS_FAILURE: "GET_SUBMISSION_DETAILS_FAILURE",
  GET_ONE_SUBMISSION_DETAIL_REQUEST: "GET_ONE_SUBMISSION_DETAIL_REQUEST",
  GET_ONE_SUBMISSION_DETAIL_SUCCESS: "GET_ONE_SUBMISSION_DETAIL_SUCCESS",
  GET_ONE_SUBMISSION_DETAIL_FAILURE: "GET_ONE_SUBMISSION_DETAIL_FAILURE",
  ADD_SUBMISSION_FILE_REQUEST: "ADD_SUBMISSION_FILE_REQUEST",
  ADD_SUBMISSION_FILE_SUCCESS: "ADD_SUBMISSION_FILE_SUCCESS",
  ADD_SUBMISSION_FILE_FAILURE: "ADD_SUBMISSION_FILE_FAILURE",
};

export const templateConstants = {
  GET_ALL_TEMPLATES_REQUEST: "GET_ALL_TEMPLATES_REQUEST",
  GET_ALL_TEMPLATES_SUCCESS: "GET_ALL_TEMPLATES_SUCCESS",
  GET_ALL_TEMPLATES_FAILURE: "GET_ALL_TEMPLATES_FAILURE",
};

export const topicConstants = {
  // GET_ALL_THEATER_REQUEST: "GET_ALL_THEATER_REQUEST",
  // GET_ALL_THEATER_SUCCESS: "GET_ALL_THEATER_SUCCESS",
  // GET_ALL_THEATER_FAILURE: "GET_ALL_THEATER_FAILURE",
  ADD_NEW_TOPIC_REQUEST: "ADD_NEW_TOPIC_REQUEST",
  ADD_NEW_TOPIC_SUCCESS: "ADD_NEW_TOPIC_SUCCESS",
  ADD_NEW_TOPIC_FAILURE: "ADD_NEW_TOPIC_FAILURE",
};

export const panelConstants = {
  GET_ALL_PANEL_REQUEST: "GET_ALL_PANEL_REQUEST",
  GET_ALL_PANEL_SUCCESS: "GET_ALL_PANEL_SUCCESS",
  GET_ALL_PANEL_FAILURE: "GET_ALL_PANEL_FAILURE",
};

export const memberConstants = {
  MEMBER_REGISTER_REQUEST: "MEMBER_REGISTER_REQUEST",
  MEMBER_REGISTER_SUCCESS: "MEMBER_REGISTER_SUCCESS",
  MEMBER_REGISTER_FAILURE: "MEMBER_REGISTER_FAILURE",
  GET_MEMBER_REQUEST: "GET_MEMBER_REQUEST",
  GET_MEMBER_SUCCESS: "GET_MEMBER_SUCCESS",
  GET_MEMBER_FAILURE: "GET_MEMBER_FAILURE",
};

export const memebersConstants = {
  GET_ALL_MEMBERS_REQUEST: "GET_ALL_MEMBERS_REQUEST",
  GET_ALL_MEMBERS_SUCCESS: "GET_ALL_MEMBERS_SUCCESS",
  GET_ALL_MEMBERS_FAILURE: "GET_ALL_MEMBERS_FAILURE",
  GET_ALL_STAFF_MEMBERS_REQUEST: "GET_ALL_STAFF_MEMBERS_REQUEST",
  GET_ALL_STAFF_MEMBERS_SUCCESS: "GET_ALL_STAFF_MEMBERS_SUCCESS",
  GET_ALL_STAFF_MEMBERS_FAILURE: "GET_ALL_STAFF_MEMBERS_FAILURE",
  GET_ALL_SUPERVISORS_REQUEST: "GET_ALL_SUPERVISORS_REQUEST",
  GET_ALL_SUPERVISORS_SUCCESS: "GET_ALL_SUPERVISORS_SUCCESS",
  GET_ALL_SUPERVISORS_FAILURE: "GET_ALL_SUPERVISORS_FAILURE",
};
