export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

// export const categoryConstants = {
//     GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
//     GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
//     GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE',
//     ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
//     ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
//     ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE',
//     UPDATE_CATEGORY_REQUEST:'UPDATE_CATEGORY_REQUEST',
//     UPDATE_CATEGORY_SUCCESS:'UPDATE_CATEGORY_SUCCESS',
//     UPDATE_CATEGORY_FAILURE:'UPDATE_CATEGORY_FAILURE',
//     DELETE_CATEGORY_REQUEST:'DELETE_CATEGORY_REQUEST',
//     DELETE_CATEGORY_SUCCESS:'DELETE_CATEGORY_SUCCESS',
//     DELETE_CATEGORY_FAILURE:'DELETE_CATEGORY_FAILURE'
// }

// export const productConstants = {
//     GET_ALL_PRODUCT_REQUEST:'GET_ALL_PRODUCT_REQUEST',
//     GET_ALL_PRODUCT_SUCCESS:'GET_ALL_PRODUCT_SUCCESS',
//     GET_ALL_PRODUCT_FAILURE:'GET_ALL_PRODUCT_FAILURE',
//     ADD_NEW_PRODUCT_REQUEST:'ADD_NEW_PRODUCT_REQUEST',
//     ADD_NEW_PRODUCT_SUCCESS:'ADD_NEW_PRODUCT_SUCCESS',
//     ADD_NEW_PRODUCT_FAILURE:'ADD_NEW_PRODUCT_FAILURE'
// }

// export const initialDataConstants = {
//     GET_ALL_initialData_REQUEST:'GET_ALL_initialData_REQUEST',
//     GET_ALL_initialData_SUCCESS:'GET_ALL_initialData_SUCCESS',
//     GET_ALL_initialData_FAILURE:'GET_ALL_initialData_FAILURE'
// }

// export const pageConstants = {
//     CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
//     CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
//     CREATE_PAGE_FAILURE:'CREATE_PAGE_FAILURE'
// };
